### ISSUE TITLE
Optionally disable X509 validation

### ISSUE THREAD

**Issue by tsbatista** [bartkessels/getit#15]
Some of us run our private APIs over https with an invalid certificate (self signed or private CA). This application should allow a user to optionally disable certificate validation, so that the end user does not need to fiddle with system wide trust stores.

Basically, what I am saying is that we should have a checkbox somewhere that makes the equivalent of calling `curl -k` on a per request basis. Would you consider adding something like that?

**Comment by bartkessels** [comment]
I'll add a setting to disable / enable X509 validation

**Comment by bartkessels** [comment]
Option added in 95d6227e5180be88731c4b36ece30e09595a3beb, will be in the next release

**Comment by bartkessels** [comment]
Release https://github.com/bartkessels/getit/releases/tag/4.0.6 contains the feature to enable / disable X.509 certificate validation
