### ISSUE TITLE
Rewrite to QT

### ISSUE THREAD

**Issue by bartkessels** [bartkessels/GetIt#21]
Rewrite application to the QT framework for cross-platform support

GTK version will be kept in separate branch

**Comment by edhelas** [comment]
What is the state of that ticket ?

**Comment by bartkessels** [comment]
The basics of the class diagram is modelled, right now I'm building the basic structure of the domain layer and trying to get catch2 to work with the qt application. When the first test-case works I'm pushing to the `qt_rewrite` branch

**Comment by bartkessels** [comment]
Checkout the development branch for a stable Qt version, note that this version isn't completely feature-par with the GTK version but development is still in progress.
