### ISSUE TITLE
Passing newline, "\n", in Key Value Pair

### ISSUE THREAD

**Issue by kmeyerhofer** [bartkessels/getit#23]
I'm trying to pass a newline character as a Form Data text value and I'm unable to stop GetIt from escaping the `\n`. My program shows the parameter sent from GetIt as displaying `\\n`.

I've tried the following:
* `\\n` which gets expanded to `\\\\n`
* `\"\n\"` which gets expanded to `\\&quot;\\n\\&quot;`
* `%0D%0A` which stays the same.

How can I pass a newline character as a form data text key value pair?

Thank you.

**Comment by bartkessels** [comment]
Hey @kmeyerhofer,

I've tried recreating the problem but it doesnt occur when I use a small PHP test script

```
<?php

print_r($_REQUEST);
```

This shows the \n character as \n, could you provide a small portion of code in which GetIt doesn't escape the character?

**Comment by kmeyerhofer** [comment]
Thanks for replying @bartkessels.
I am using the ruby framework Sinatra and I believe there is an underlying escaping going on at the framework level. 
I'm going to close the issue and work on looking for a solution in ruby.
Thanks for looking into it.
