### ISSUE TITLE
Please bump version

### ISSUE THREAD

**Issue by xarbit** [bartkessels/getit#26]
Hi, 
can you please accept my pull request and release a new bugfix version. 
flatpak is giving me warnings that the platform 3.32 is not supported any more and needs to be updated.
I went ahead and updated the flatpak manifest to use 3.36 (which worked locally) and created a pull request.. 

Ref:
https://github.com/bartkessels/getit/pull/25
https://github.com/flathub/net.bartkessels.getit/pull/3

**Comment by bartkessels** [comment]
Hey, your pull request has been accepted. Sorry for the long wait
