### ISSUE TITLE
Don't use application menu

### ISSUE THREAD

**Issue by TomaszGasior** [bartkessels/GetIt#29]
Please don't use GTK's application menu. It's deprecated in GNOME design guideline. Instead, move all its contents to the "hamburger" menu.

**Comment by bartkessels** [comment]
This isn't going to be implemented 'cause of the rewrite to Qt no specific GNOME design guidelines are adhered. If you're able to provide a PR to the master branch then I'll merge it for the GTK version (the GTK version will stay up on the master branch, but it won't be actively maintained in favour of the Qt version). Therefore I'm going to close this issue, please open a PR which addresses this issue.

**Comment by TomaszGasior** [comment]
I didn't know there is a plan for Qt rewrite. :) There is no way to implement GNOME guidelines in Qt so yeah, it makes sense to just close this issue.
