### ISSUE TITLE
Create release with oars

### ISSUE THREAD

**Issue by cpba** [bartkessels/GetIt#30]
`4.0.9` fails to build on flathub because the [appstream validation has been made stricter and now requires oars.](https://github.com/flathub/net.bartkessels.getit/pull/4)

This was added to GetIt back in april #25.

However, no new releases have been made since then, so flathub can't build the last stable release.

As this is quite a small change with very little chance of causing harm, would you be open to making a new point release that included it?

Alternatively, if you think that would be better for you, the flatpak manifest could be changed to point to latest git master instead.

**Comment by bartkessels** [comment]
Hi,

Sorry for the late responses (if I've given any) but I've been very busy with school work lately. But I've created a new release for GetIt (2d7eadbc477ff159f44f650f906e9065b944371a).

Hopefully this will work, I'll keep this issue open until it works and the flatpack package builds.

I've been working on other projects as well so in the future the releases for GetIt on Flathub can be automated.

Kind regards

**Comment by cpba** [comment]
@bartkessels sorry to bother you again, I know this is a silly thing, but this introduced a new problem.

The content rating tag had already been introduced in https://github.com/bartkessels/GetIt/commit/8bd642c48b2acfa32ade6f813a25ff5694126df2, now https://github.com/bartkessels/GetIt/commit/2d7eadbc477ff159f44f650f906e9065b944371a adds it again.

This means that now there's two, one at line 11: https://github.com/bartkessels/GetIt/blob/3e289cd18798b77ff5ac83482dbf99c328d33bff/data/net.bartkessels.getit.appdata.xml.in#L11

And another one at line 72:
https://github.com/bartkessels/GetIt/blob/3e289cd18798b77ff5ac83482dbf99c328d33bff/data/net.bartkessels.getit.appdata.xml.in#L72

So appstream validation on `4.0.10` still fails, but because of too many tags, it's a bit funny when you think about it.

There's no rush. I realise you are very busy, we all are and this is of very little importance, just do it when you have time.

**Comment by bartkessels** [comment]
@cpba I thought that I've seen that tag in of or your PR's, but didn't realise it.

Anyways, there's a new commit which removes the second tag (b81c006b079c88a90bdddeb4eac0b419cf221bc2).
The release 4.0.10 is also re-created

**Comment by cpba** [comment]
@bartkessels thank you, it builds perfectly now. I'll close this issue, https://github.com/flathub/net.bartkessels.getit/pull/4 is ready to merge whenever you want.
